import {
  LOTTO_MAX_NUMBER,
  LOTTO_MIN_NUMBER,
  LOTTO_NUMBER_COUNT,
  LOTTO_PRICE_UNIT,
  MAX_PURCHASE_AMOUNT,
  MIN_PURCHASE_AMOUNT,
} from "./rules.js";

export const ERROR_MESSAGE = {
  INVALID_NUMBER: "숫자를 입력해주세요.",
  INVALID_LOTTO_PRICE_UNIT: `${LOTTO_PRICE_UNIT}원 단위로 입력해주세요.`,
  INVALID_PRICE_RANGE: `${MIN_PURCHASE_AMOUNT}원 이상 ${MAX_PURCHASE_AMOUNT / 10000}만원 이하로 입력해주세요.`,
  INVALID_LOTTO_NUMBER_RANGE: `${LOTTO_MIN_NUMBER}부터 ${LOTTO_MAX_NUMBER} 사이의 숫자를 입력해주세요.`,
  INVALID_LOTTO_NUMBER_LENGTH: `${LOTTO_NUMBER_COUNT}개의 숫자를 입력해주세요.`,
  INVALID_LOTTO_DUPLICATE_NUMBER: "중복된 숫자가 있습니다.",
  INVALID_BONUS_NUMBER: "당첨 번호와 중복되지 않는 숫자를 입력해주세요.",
  INVALID_RESTART_FORMAT: "y 또는 n을 입력해주세요.",
};
